pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f dockerprac/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        /*stage('Create Tomcat Docker Image'){
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build ./dockerprac -t dockerprac:${env.BUILD_ID}"
            }
        }*/

    }
}
